#!/bin/bash

# Function to check if the argument is a number
is_number() {
    if [[ "$1" =~ ^[0-9]+(\.[0-9]+)?$ ]]; then
        return 0  # Argument is a number
    else
        return 1  # Argument is not a number
    fi
}

# Main script
if [[ $# -lt 1 ]]; then
    echo "Usage: $0 <processList>"
    exit 1
fi

for i in $@; do
	argument="$i"
	#echo $argument
	if is_number "$argument"; then
    	#echo "$argument is a number."
		./memusage -p $argument
	else
    	#echo "$argument is a string."
		./memusage $argument
	fi

done


