#!/bin/bash
# ======================================================================================
# USAGE:
#
#    Lets say you have proj1, proj2, proj3 and proj4 in your current directory and you
#    want to seach all but proj3 for a file called fileoutput.c then you use
#
#    exfind . -v proj3 -name 'fileoutput.c'
#
#    If the same situation is there in your workplace folder then also it works.
#
#    exfind workspace -v proj3 -iname 'fileoutput.c'
#=======================================================================================
#To Do:
#	Allow list of directories to be exclued. Should the list be in ""? or it should be 
#   a comma separated list?
########################################################################################


DIRECTORY=""
if [[ "$2" = "-v" ]]; then
	#echo "exclusion found"
	DIRECTORY=$3
fi

if [[ ${DIRECTORY} != "" ]]; then
	SEARCHPATH=$(ls -1d $1/* | grep -v ${DIRECTORY} | tr '\n\r' ' ' | sed 's/ $/\n/')	
	#echo $SEARCHPATH
	shift 3
	DEFAULT="$@"
	#echo $DEFAULT
else 
	SEARCHPATH=$2
	find $@
	exit 0
fi

#echo "EXCLUDE DIRECTORY  = ${DIRECTORY}"
#echo "SEARCH PATH     = ${SEARCHPATH}"
#echo "DEFAULT         = ${DEFAULT}"

#if [[ -n $1 ]]; then
#    echo "Last line of file specified as non-opt/last argument:"
#    tail -1 "$1"
#fi


find $SEARCHPATH $DEFAULT
#find "$@"
